### ISSUE TITLE
After update retrofit 2.7.0 required JAVA 1.8

### ISSUE THREAD

**Issue by attaullahpro** [square/retrofit#3268]
After updating retrofit 2.7.0 required JAVA 1.8 but the issue is that the App is crashing on some of the mobile devices while using JAVA 1.8 so please resolve such issues. I notice there no issue in my code but after using JAVA 1.8 a lot of with retrofit 2.7.0 crashes occur.

**Comment by JakeWharton** [comment]
You have provided no information about the crash to result in anything actionable from our side. Please include, at minimum, a full stacktrace. Any other information upto and including an executable sample that reproduces the issue is also welcome.

**Comment by lavsexpert** [comment]
I have another problem.
When I use Retrofit 2.6.3 - all a worked (and now worked, when I downgrade to 2.6.3)
But when I upgrade to 2.7.0 I'we got crush.
Stack trace:

`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.electric.ec.online, PID: 15740
    java.lang.BootstrapMethodError: Exception from call site #8 bootstrap method
        at okhttp3.logging.HttpLoggingInterceptor$Logger.<clinit>(HttpLoggingInterceptor.java:112)
        at okhttp3.logging.HttpLoggingInterceptor.<init>(HttpLoggingInterceptor.java:116)
        at ru.electric.ec.online.models.ServerNetwork.<init>(ServerNetwork.java:43)
        at ru.electric.ec.online.models.ServerNetwork.getInstance(ServerNetwork.java:36)
        at ru.electric.ec.online.viewmodels.App.onCreate(App.java:20)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NoClassDefFoundError: Invalid descriptor: downPreScrollRange.
        at okhttp3.logging.HttpLoggingInterceptor$Logger.<clinit>(HttpLoggingInterceptor.java:112) 
        at okhttp3.logging.HttpLoggingInterceptor.<init>(HttpLoggingInterceptor.java:116) 
        at ru.electric.ec.online.models.ServerNetwork.<init>(ServerNetwork.java:43) 
        at ru.electric.ec.online.models.ServerNetwork.getInstance(ServerNetwork.java:36) 
        at ru.electric.ec.online.viewmodels.App.onCreate(App.java:20) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
`

**Comment by lavsexpert** [comment]
the function when I've got this exception:

`
    private ServerNetwork() {

        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(BuildConfig.DEBUG ? HttpLoggingInterceptor.Level.BODY : HttpLoggingInterceptor.Level.NONE);

        Gson gson = new GsonBuilder().setLenient().create();
        retrofit = new Retrofit.Builder()
                .baseUrl("https://www.ec-electric.ru/api/v1/")
                .addConverterFactory(GsonConverterFactory.create(gson))
                .client(getUnsafeOkHttpClient())
                .build();

        serverApi = retrofit.create(ServerApi.class);

        handler = new Handler(Looper.getMainLooper());
    }

`

**Comment by lavsexpert** [comment]
dependences when app worked correctly:
    implementation 'com.squareup.okhttp3:logging-interceptor:3.14.4'
    implementation 'com.squareup.retrofit2:retrofit:2.6.3'
    implementation 'com.squareup.retrofit2:converter-gson:2.6.3'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.6.3'

dependences with crush:
    implementation 'com.squareup.okhttp3:logging-interceptor:3.14.4'
    implementation 'com.squareup.retrofit2:retrofit:2.7.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.7.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.7.0'

**Comment by lavsexpert** [comment]
I'we got same App crash after update to 2.7.0
But I fix this problem after read how to update to Java 1.8:
[https://cashapp.github.io/2019-02-05/okhttp-3-13-requires-android-5](https://cashapp.github.io/2019-02-05/okhttp-3-13-requires-android-5)

when add to build.gradle:
android {
...
    compileOptions {
        targetCompatibility = "8"
        sourceCompatibility = "8"
    }
}

**Comment by attaullahpro** [comment]
I resolve my issue but it need API 21 why, some of my project need API 16

**Comment by lavsexpert** [comment]
> I resolve my issue but it need API 21 why, some of my project need API 16

I think that you cat downgrade to 2.6.3 to fix your problem. Because 2.7.0 [minimum requirements to Java 8+ or Android 5+](https://github.com/square/retrofit/blob/master/CHANGELOG.md)
